# Generated by Django 4.2.7 on 2025-09-27 16:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_points', models.PositiveIntegerField(default=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section')),
            ],
            options={
                'verbose_name': 'Grade Component',
                'verbose_name_plural': 'Grade Components',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.gradecomponent')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'unique_together': {('student', 'component')},
            },
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerical_grade', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('letter_grade', models.CharField(choices=[('A+', 'A+ (95-100)'), ('A', 'A (90-94)'), ('A-', 'A- (85-89)'), ('B+', 'B+ (80-84)'), ('B', 'B (75-79)'), ('B-', 'B- (70-74)'), ('C+', 'C+ (65-69)'), ('C', 'C (60-64)'), ('C-', 'C- (55-59)'), ('D', 'D (50-54)'), ('F', 'F (Below 50)'), ('I', 'Incomplete'), ('W', 'Withdrawn')], max_length=2)),
                ('gpa_points', models.FloatField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Final Grade',
                'verbose_name_plural': 'Final Grades',
                'unique_together': {('student', 'section')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='submissions/')),
                ('comments', models.TextField(blank=True)),
                ('points_earned', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_graded', models.BooleanField(default=False)),
                ('graded_date', models.DateTimeField(blank=True, null=True)),
                ('teacher_comments', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
