# Generated by Django 4.2.7 on 2025-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_pronouns',
            field=models.CharField(blank=True, help_text='e.g., he/him, she/her, they/them', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='pronunciation_guide',
            field=models.CharField(blank=True, help_text='How to pronounce your name', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='office_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='research_interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
