# Generated by Django 4.2.7 on 2025-09-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('attendance', '0002_alter_attendancesession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('section', 'date')},
        ),
    ]
